name: Auto Sync Fork with Upstream

# 触发条件：每6小时自动同步 + 支持手动触发
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Upstream
        uses: dabreadman/sync-upstream@v1
        with:
          upstream: anghunk/cwd
          upstream-branch: main
          branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
          git_pull_args: --ff-only
